name: workout_timer
description: A beautiful interval workout timer with voice cues, custom workouts, and workout tracking.
version: 0.2.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  # flutter_tts: ^4.2.3
  # geolocator: ^14.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
